import { User, Task, Submission, Transaction, Notification, Conversation, Message, AnalyticsData, WalletData } from "./types";

export const mockUser: User = {
  id: "usr_001",
  name: "Arjun Mehta",
  email: "arjun@Task-Marketplace.io",
  role: "contributor",
  avatar: "",
  department: "Computer Science",
  year: "3rd Year",
  college: "IIT Delhi",
  skills: ["UI/UX Design", "Web Development", "Graphic Design", "React", "Figma"],
  bio: "Creative developer and designer passionate about building beautiful digital experiences.",
  portfolioLinks: ["https://dribbble.com/arjun", "https://github.com/arjunmehta"],
  rating: 4.8,
  totalTasks: 47,
  totalEarnings: 125000,
  totalWins: 23,
  isVerified: true,
  joinedAt: "2025-08-15",
};

export const mockClient: User = {
  id: "usr_002",
  name: "Priya Sharma",
  email: "priya@Task-Marketplace.io",
  role: "client",
  avatar: "",
  department: "Marketing",
  year: "4th Year",
  college: "IIT Delhi",
  skills: [],
  bio: "Event organizer and marketing enthusiast. Always looking for creative talent.",
  rating: 4.9,
  totalTasks: 32,
  totalEarnings: 0,
  totalWins: 0,
  isVerified: true,
  joinedAt: "2025-06-20",
};

export const mockTasks: Task[] = [
  {
    id: "task_001",
    title: "Design a Modern Event Poster for TechFest 2026",
    description: "We need a stunning, eye-catching poster for our annual technical festival. The design should be futuristic, vibrant, and appeal to college students. Include the event name, date (March 15-17, 2026), venue, and key highlights.",
    requirements: "- A4 size (300 DPI)\n- Include event logo\n- Futuristic theme with tech elements\n- Color scheme: Dark with neon accents\n- Must include QR code placeholder\n- Submit in PSD/AI + PNG format",
    category: "graphic-design",
    tags: ["poster", "event", "techfest", "design"],
    budget: 5000,
    deadline: "2026-05-20",
    priority: "high",
    status: "open",
    visibility: "public",
    submissionType: "Image/Poster",
    maxWinners: 1,
    attachments: [],
    client: mockClient,
    submissionCount: 14,
    createdAt: "2026-05-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "task_002",
    title: "Build a Portfolio Website Landing Page",
    description: "Looking for a creative developer to build a responsive, animated portfolio landing page. Should be modern, minimal, and impressive. Think Stripe/Linear quality.",
    requirements: "- React or Next.js\n- Fully responsive\n- Smooth animations\n- Dark theme\n- Fast loading\n- Deploy-ready code",
    category: "web-development",
    tags: ["website", "portfolio", "react", "nextjs", "frontend"],
    budget: 8000,
    deadline: "2026-05-25",
    priority: "medium",
    status: "open",
    visibility: "public",
    submissionType: "Code/Website",
    maxWinners: 1,
    attachments: [],
    client: { ...mockClient, id: "usr_003", name: "Rahul Verma" },
    submissionCount: 8,
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
  },
  {
    id: "task_003",
    title: "Create Instagram Reels for College Fest Promotion",
    description: "We need 3 short-form video reels (15-30 seconds each) promoting our cultural fest. High energy, trending music, dynamic transitions.",
    requirements: "- 9:16 aspect ratio\n- 15-30 seconds each\n- Trending audio compatible\n- Include event details overlay\n- Export in MP4 (1080x1920)",
    category: "video-editing",
    tags: ["video", "reels", "instagram", "promotion", "editing"],
    budget: 6000,
    deadline: "2026-05-18",
    priority: "urgent",
    status: "open",
    visibility: "public",
    submissionType: "Video",
    maxWinners: 1,
    attachments: [],
    client: { ...mockClient, id: "usr_004", name: "Sneha Patel" },
    submissionCount: 5,
    createdAt: "2026-05-03",
    updatedAt: "2026-05-03",
  },
  {
    id: "task_004",
    title: "Write Technical Blog Posts for Developer Community",
    description: "Need 5 well-researched technical articles on trending topics like AI/ML, Web3, and Cloud Computing. Each article should be 1500-2000 words.",
    requirements: "- 1500-2000 words per article\n- SEO optimized\n- Include code snippets where relevant\n- Original content only\n- Submit in Markdown format",
    category: "content-writing",
    tags: ["blog", "technical", "writing", "ai", "web3"],
    budget: 4000,
    deadline: "2026-05-30",
    priority: "low",
    status: "open",
    visibility: "public",
    submissionType: "Document",
    maxWinners: 1,
    attachments: [],
    client: { ...mockClient, id: "usr_005", name: "Karan Singh" },
    submissionCount: 12,
    createdAt: "2026-05-01",
    updatedAt: "2026-05-01",
  },
  {
    id: "task_005",
    title: "Design Mobile App UI for Campus Food Delivery",
    description: "Complete UI/UX design for a food delivery app targeting college campuses. Need all major screens — onboarding, home, menu, cart, checkout, tracking, profile.",
    requirements: "- Figma file required\n- Minimum 15 screens\n- Include component library\n- Dark + Light variants\n- Mobile-first (iOS + Android)\n- Include prototype links",
    category: "ui-ux-design",
    tags: ["ui", "ux", "mobile", "app", "figma", "food"],
    budget: 12000,
    deadline: "2026-06-10",
    priority: "high",
    status: "open",
    visibility: "public",
    submissionType: "Design File",
    maxWinners: 2,
    attachments: [],
    client: { ...mockClient, id: "usr_006", name: "Ananya Gupta" },
    submissionCount: 7,
    createdAt: "2026-05-04",
    updatedAt: "2026-05-04",
  },
  {
    id: "task_006",
    title: "Campus Photography — Student Life Series",
    description: "Looking for a talented photographer to capture authentic campus life moments. 20 high-quality photos showcasing student activities, events, and campus beauty.",
    requirements: "- 20 photos minimum\n- High resolution (min 4000px wide)\n- Candid + posed mix\n- Light editing allowed\n- Submit RAW + edited JPGs\n- No heavy filters",
    category: "photography",
    tags: ["photography", "campus", "student-life", "portrait"],
    budget: 3500,
    deadline: "2026-05-22",
    priority: "medium",
    status: "in-progress",
    visibility: "college-only",
    submissionType: "Photos",
    maxWinners: 1,
    attachments: [],
    client: { ...mockClient, id: "usr_007", name: "Vikram Rao" },
    submissionCount: 3,
    createdAt: "2026-04-28",
    updatedAt: "2026-05-03",
  },
  {
    id: "task_007",
    title: "Social Media Content Calendar & Posts",
    description: "Create a 30-day social media content calendar with 60 ready-to-post graphics for Instagram, LinkedIn, and Twitter for our college startup club.",
    requirements: "- 60 post designs (20 per platform)\n- Content calendar spreadsheet\n- Brand guidelines adherence\n- Mix of carousel, single, story\n- Canva editable + PNG exports",
    category: "social-media",
    tags: ["social-media", "content", "instagram", "linkedin", "marketing"],
    budget: 7500,
    deadline: "2026-06-01",
    priority: "medium",
    status: "open",
    visibility: "public",
    submissionType: "Design + Document",
    maxWinners: 1,
    attachments: [],
    client: { ...mockClient, id: "usr_008", name: "Meera Nair" },
    submissionCount: 6,
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
  },
  {
    id: "task_008",
    title: "Data Visualization Dashboard for Placement Stats",
    description: "Build an interactive dashboard visualizing our college placement statistics for the past 5 years. Should include charts, filters, and export functionality.",
    requirements: "- Interactive charts (bar, line, pie)\n- Filter by year, department, company\n- Export to PDF\n- Responsive design\n- Use real-looking sample data\n- React + Chart.js or D3",
    category: "data-analytics",
    tags: ["dashboard", "data-viz", "charts", "analytics", "react"],
    budget: 10000,
    deadline: "2026-06-15",
    priority: "high",
    status: "open",
    visibility: "public",
    submissionType: "Code/Website",
    maxWinners: 1,
    attachments: [],
    client: { ...mockClient, id: "usr_009", name: "Aditya Kumar" },
    submissionCount: 4,
    createdAt: "2026-05-05",
    updatedAt: "2026-05-05",
  },
];

export const mockSubmissions: Submission[] = [
  {
    id: "sub_001",
    taskId: "task_001",
    task: mockTasks[0],
    contributor: mockUser,
    files: [{ id: "file_001", name: "techfest-poster-v2.png", url: "#", type: "image/png", size: 4500000 }],
    comment: "Here's my take on the TechFest poster. Used a cyberpunk-inspired design with neon gradients. Let me know if you'd like any revisions!",
    status: "shortlisted",
    rating: 4,
    version: 2,
    submittedAt: "2026-05-05",
    updatedAt: "2026-05-05",
  },
  {
    id: "sub_002",
    taskId: "task_002",
    task: mockTasks[1],
    contributor: { ...mockUser, id: "usr_010", name: "Riya Kapoor" },
    files: [{ id: "file_002", name: "portfolio-site.zip", url: "#", type: "application/zip", size: 12000000 }],
    comment: "Built with Next.js 14, Framer Motion, and Tailwind. Fully responsive with smooth scroll animations. Live preview: https://demo.link",
    status: "pending",
    version: 1,
    submittedAt: "2026-05-04",
    updatedAt: "2026-05-04",
  },
  {
    id: "sub_003",
    taskId: "task_005",
    task: mockTasks[4],
    contributor: { ...mockUser, id: "usr_011", name: "Dev Sharma" },
    files: [{ id: "file_003", name: "food-app-ui.fig", url: "#", type: "application/figma", size: 8500000 }],
    comment: "18 screens designed in Figma with a complete component library. Includes dark and light mode. Interactive prototype included.",
    status: "winner",
    rating: 5,
    version: 1,
    submittedAt: "2026-05-03",
    updatedAt: "2026-05-06",
  },
];

export const mockTransactions: Transaction[] = [
  { id: "txn_001", type: "payout", amount: 5000, status: "completed", description: "Winner payout for TechFest Poster Design", taskId: "task_001", createdAt: "2026-05-05" },
  { id: "txn_002", type: "payout", amount: 8000, status: "pending", description: "Pending payout for Portfolio Website", taskId: "task_002", createdAt: "2026-05-04" },
  { id: "txn_003", type: "deposit", amount: 20000, status: "completed", description: "Wallet top-up via UPI", createdAt: "2026-05-03" },
  { id: "txn_004", type: "payout", amount: 12000, status: "completed", description: "Winner payout for Mobile App UI Design", taskId: "task_005", createdAt: "2026-05-02" },
  { id: "txn_005", type: "withdrawal", amount: 15000, status: "completed", description: "Bank withdrawal to SBI Account", createdAt: "2026-05-01" },
  { id: "txn_006", type: "payout", amount: 3500, status: "completed", description: "Winner payout for Campus Photography", taskId: "task_006", createdAt: "2026-04-30" },
  { id: "txn_007", type: "deposit", amount: 10000, status: "completed", description: "Wallet top-up via Card", createdAt: "2026-04-28" },
  { id: "txn_008", type: "refund", amount: 2000, status: "completed", description: "Refund for cancelled task", createdAt: "2026-04-25" },
];

export const mockNotifications: Notification[] = [
  { id: "notif_001", type: "submission", title: "New Submission Received", message: "Arjun Mehta submitted work for 'TechFest Poster Design'", read: false, actionUrl: "/dashboard/submissions", createdAt: "2026-05-06T10:30:00" },
  { id: "notif_002", type: "payout", title: "Payout Processed", message: "₹5,000 has been credited to your wallet", read: false, actionUrl: "/dashboard/wallet", createdAt: "2026-05-06T09:15:00" },
  { id: "notif_003", type: "task", title: "Deadline Approaching", message: "Task 'Instagram Reels' deadline is in 2 days", read: false, actionUrl: "/tasks/task_003", createdAt: "2026-05-06T08:00:00" },
  { id: "notif_004", type: "submission", title: "Submission Shortlisted!", message: "Your submission for 'TechFest Poster' has been shortlisted", read: true, actionUrl: "/dashboard/submissions", createdAt: "2026-05-05T16:45:00" },
  { id: "notif_005", type: "message", title: "New Message", message: "Priya Sharma sent you a message about 'Portfolio Website'", read: true, actionUrl: "/dashboard/messages", createdAt: "2026-05-05T14:20:00" },
  { id: "notif_006", type: "system", title: "Welcome to Task-Marketplace!", message: "Your account has been verified. Start exploring tasks!", read: true, actionUrl: "/tasks", createdAt: "2026-05-01T10:00:00" },
];

export const mockConversations: Conversation[] = [
  {
    id: "conv_001",
    participants: [mockUser, mockClient],
    taskId: "task_001",
    taskTitle: "Design a Modern Event Poster for TechFest 2026",
    lastMessage: {
      id: "msg_001",
      senderId: mockClient.id,
      senderName: mockClient.name,
      content: "Love the direction! Can you try a version with more blue tones?",
      read: false,
      createdAt: "2026-05-06T10:30:00",
    },
    unreadCount: 2,
    updatedAt: "2026-05-06T10:30:00",
  },
  {
    id: "conv_002",
    participants: [mockUser, { ...mockClient, id: "usr_003", name: "Rahul Verma" }],
    taskId: "task_002",
    taskTitle: "Build a Portfolio Website Landing Page",
    lastMessage: {
      id: "msg_002",
      senderId: mockUser.id,
      senderName: mockUser.name,
      content: "I've deployed the latest version. Check the preview link!",
      read: true,
      createdAt: "2026-05-05T15:00:00",
    },
    unreadCount: 0,
    updatedAt: "2026-05-05T15:00:00",
  },
  {
    id: "conv_003",
    participants: [mockUser, { ...mockClient, id: "usr_006", name: "Ananya Gupta" }],
    taskId: "task_005",
    taskTitle: "Design Mobile App UI for Campus Food Delivery",
    lastMessage: {
      id: "msg_003",
      senderId: "usr_006",
      senderName: "Ananya Gupta",
      content: "The prototype looks amazing. Can we discuss the checkout flow?",
      read: true,
      createdAt: "2026-05-04T11:45:00",
    },
    unreadCount: 0,
    updatedAt: "2026-05-04T11:45:00",
  },
];

export const mockMessages: Message[] = [
  { id: "msg_101", senderId: mockClient.id, senderName: "Priya Sharma", content: "Hi Arjun! Thanks for your submission on the TechFest poster.", read: true, createdAt: "2026-05-05T09:00:00" },
  { id: "msg_102", senderId: mockUser.id, senderName: "Arjun Mehta", content: "Thanks Priya! Happy to make any adjustments you need.", read: true, createdAt: "2026-05-05T09:15:00" },
  { id: "msg_103", senderId: mockClient.id, senderName: "Priya Sharma", content: "The overall design is great. Could you try a version with more blue/cyan tones to match our brand?", read: true, createdAt: "2026-05-05T09:30:00" },
  { id: "msg_104", senderId: mockUser.id, senderName: "Arjun Mehta", content: "Absolutely! I'll work on a blue variant and have it ready by tomorrow. Also, would you like me to adjust the typography?", read: true, createdAt: "2026-05-05T09:45:00" },
  { id: "msg_105", senderId: mockClient.id, senderName: "Priya Sharma", content: "The typography is perfect as is. Just the color shift would be great. Thanks!", read: true, createdAt: "2026-05-05T10:00:00" },
  { id: "msg_106", senderId: mockUser.id, senderName: "Arjun Mehta", content: "Got it! I'll send over the updated version shortly.", read: true, createdAt: "2026-05-05T10:10:00" },
  { id: "msg_107", senderId: mockClient.id, senderName: "Priya Sharma", content: "Love the direction! Can you try a version with more blue tones?", read: false, createdAt: "2026-05-06T10:30:00" },
];

export const mockWallet: WalletData = {
  balance: 28500,
  pendingAmount: 8000,
  totalEarnings: 125000,
  totalWithdrawals: 88500,
  transactions: mockTransactions,
};

export const mockAnalytics: AnalyticsData = {
  tasksPosted: 32,
  tasksCompleted: 28,
  submissionsReceived: 156,
  avgRating: 4.8,
  totalSpent: 185000,
  totalEarned: 125000,
  monthlyData: [
    { month: "Jan", tasks: 3, earnings: 8000, submissions: 12 },
    { month: "Feb", tasks: 5, earnings: 15000, submissions: 22 },
    { month: "Mar", tasks: 4, earnings: 12000, submissions: 18 },
    { month: "Apr", tasks: 6, earnings: 22000, submissions: 31 },
    { month: "May", tasks: 8, earnings: 28000, submissions: 42 },
    { month: "Jun", tasks: 2, earnings: 8000, submissions: 8 },
    { month: "Jul", tasks: 4, earnings: 12000, submissions: 15 },
    { month: "Aug", tasks: 3, earnings: 5000, submissions: 8 },
  ],
  categoryBreakdown: [
    { category: "Graphic Design", count: 12, percentage: 35 },
    { category: "Web Development", count: 8, percentage: 24 },
    { category: "UI/UX Design", count: 6, percentage: 18 },
    { category: "Video Editing", count: 4, percentage: 12 },
    { category: "Content Writing", count: 2, percentage: 6 },
    { category: "Other", count: 2, percentage: 5 },
  ],
  recentActivity: [
    { action: "Submission received", timestamp: "2026-05-06T10:30:00", details: "New submission on TechFest Poster task" },
    { action: "Task completed", timestamp: "2026-05-05T16:00:00", details: "Mobile App UI Design marked as complete" },
    { action: "Payout processed", timestamp: "2026-05-05T09:00:00", details: "₹5,000 paid to winner" },
    { action: "New task posted", timestamp: "2026-05-04T14:00:00", details: "Data Visualization Dashboard task created" },
    { action: "Winner selected", timestamp: "2026-05-03T18:00:00", details: "Dev Sharma selected for Food App UI" },
  ],
};
